# 函数

## 函数的定义

1. 基础定义

    ```go
    func add(a, b int) int {
    return a + b
    }

    func add2(a, b int) (sum int) {
    sum = a + b
    return sum
    }

    func add3(a, b int) (sum int) {
    sum = a + b
    return
    }
    ```
    - 直接使用`func`进行定义即可，函数中的表示传入的内容以及数据类型，后面的部分表示输出的结果以及类型
    - 如果输出中直接表示的输出的变量，可以不在函数中进行定义和明确的返回
2. 返回多个值

    ```Go
    func div(a, b int) (int, error) {
    if b == 0 {
        return 0, fmt.Errorf("divided by zero")
    }
    return a / b, nil
    }

    func div2(a, b int) (result int, err error) {
    if b == 0 {
        err = fmt.Errorf("divided by zero")
        return
    }
    result = a / b
    return
    }
    ```
    - 如果需要和python一样输出多个值也是可以的
    - 也支持直接定义输出的变量以及类型
3. 函数的使用

    ```Go
    func div2(a, b int) (result int, err error) {
    if b == 0 {
        err = fmt.Errorf("divided by zero")
        return
    }
    result = a / b
    return
    }

    func main() {
    result, err := div2(10, 0)
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println(result)
    }
    }
    ```
4. 省略号的使用

    ```Go
    func add4(a int, args ...int) int {
    var sum int = a
    for _, arg := range args {
        sum += arg
    }
    return sum
    }

    func main() {
    result := add4(0, 2)
    result1 := add4(0, 2, 3)
    fmt.Println(result) // 2
    fmt.Println(result1) // 5
    slice := []int{1, 2, 3, 4}
    result2 := add4(0, slice...)
    fmt.Println(result2) // 10
    }
    ```
    - 通过省略号操作可以输入任意个数的参数
    - 也可以通过省略号将slice进行打散的操作

## 函数的性质

1. 在go中函数和python中类型，可以作为参数一样进行传递
2. 匿名函数

    ```Go
    func main() {
    // 匿名函数
    result := func(a, b int) int {
        return a + b
    }(1, 2)
    fmt.Println(result)
    }
    ```
3. 函数类型定义

    ```Go
    func main() {
    type addFunc func(int, int) int
    var f addFunc = func(a, b int) int {
        return a + b
    }
    fmt.Println(f(1, 2))
    }
    ```
4. 函数作为参数

    ```Go
    func filter(slice []int, f func(int) bool) []int {
    var result []int
    for _, value := range slice {
        if f(value) {
        result = append(result, value)
        }
    }
    return result
    }

    func main() {
    fmt.Println(filter([]int{20, 30, 50, 70, 90}, func(i int) bool {
        return i > 50
    }))

    }
    ```
    - 上面的案例中展示的筛选操作，将满足条件的数据进行保存操作
    - 但是有时筛选的逻辑比较复杂多变，因此可以将函数作为参数进行传递

## defer的使用

1. 使用python进行简单说明

    ```Python
    try:
        # 打开文件
        f = open('test.txt')
        # 处理文件
        content = f.read()
        print(content)
        # 关闭文件
        f.close()
    except:
        print('文件不存在')
    finally:
        f.close()

    ```
    - 在程序编写中时常需要同时进行两个操作，例如文件打开之后需要关闭，数据库连接之后需要断开操作，因此在python中提供了`try-except-finally`功能
    - 在上面的操作中无论是否执行成功，文件都会执行关闭操作
    - 细节说明
        ```Python
        def main():
            a = 1
            b = [1, 2, 3]
            try:
                return b
            except:
                print('文件不存在')
            finally:
                a += 1
                b.append(4)
                print(a)
                print(b)
                print('finally')
                
        if __name__ == "__main__":
            print(main())

        """
        2
        [1, 2, 3, 4]
        finally
        [1, 2, 3, 4]
        """
        ```
        - `try-except-finally`中是先执行`try` 内部的程序，将最终结果暂存成一个新变量，之后执行`finally`操作，最后执行`return`操作，`return`出去这个新变量
        - `return`内部相当于是生成了一个新的变量，因此需要注意输出的变量的类型，例如如果输出的int类型那么就是赋值操作，`finally`中的操作并不会影响`return`的结果，如果是`list`类型那么是引用赋值操作，`finally`会影响`return`的结果
2. `defer`基础使用

    ```Go
    func main() {
    fmt.Println("test1")
    defer fmt.Println("defer1")
    defer fmt.Println("defer2")
    fmt.Println("test2")
    }

    // test1
    // test2
    // defer2
    // defer1
    ```
    - `defer`类似于python中的`finally`操作，会先进行注册，最后进行执行
    - 只能传入一个函数的调用，不能传入变量的操作或者一个函数
    - 执行的顺序相当于一个栈，执行先进后出的策略
3. `defer`的细节

    ```Go
    func main() {
    x := 10
    defer func(a int) {
        fmt.Println(a) // 10
    }(x)
    x++
    }

    func main() {
    x := 10
    defer func(a *int) {
        *a++
        fmt.Println(*a) // 11
    }(&x)
    }

    func main() {
    x := 10
    defer func() {
        fmt.Println(x) // 11
    }()
    x++
    }

    func f1() int {
    x := 5
    defer func() {
        x++
    }()
    return x
    }

    func f2() *int {
    x := 5
    y := &x
    defer func() {
        *y++
    }()
    return y
    }

    func main() {
    fmt.Println(f1()) // 5
    fmt.Println(*f2()) // 6
    }

    ```
    - `defer`执行的是注册的操作，如果传入的一个变量，包含这个变量的值，那么这个值就会保存在`defer`中，后续的执行和`defer`中的输出无关，如果是一个传入的是一个指针或者不传入直接使用全局变量，那么后续的操作就会有影响
    - `defer`也是先执行完`defer`后在执行`return`操作，不过也和python类似，是首先执行到return的最后一步，保存成一个临时变量之后在去执行defer操作，因此如果是值赋值的话结果就不会发生变化，如果是引用赋值那么就会发生变化[//]: # (例如上面的f1和f2方法的区别)

## 函数的错误和异常

1. 错误和异常的区别
    - 错误（Error）
        - 在 Go 中，错误是一种常见的情况，通常表示程序在运行过程中遇到的问题。Go 语言通过一个内置的 `error` 接口来表示错误。
        - 错误是可预见的，可以通过返回值的方式进行处理。函数通常返回一个 `error` 类型的值，调用者可以检查这个值来判断是否发生了错误。
    - 异常（Exception）
        - Go 语言没有传统意义上的异常处理机制（如 `try/catch` 语句）。相反，Go 采用了简化的错误处理模型，强调显式的错误检查。
        - 在 Go 中，异常通常指的是程序运行时的严重错误，例如数组越界、空指针解引用等。这些情况可能导致程序崩溃，但在 Go 中，这些通常被视为程序逻辑错误，而不是通过异常机制处理。
2. 错误和异常的处理
    - 错误处理

        ```Go
        package main

        import (
            "fmt"
            "os"
        )

        func main() {
            file, err := os.Open("non_existing_file.txt")
            if err != nil {
                fmt.Println("打开文件时出错:", err)
                return
            }
            defer file.Close()
            // 继续处理文件
        }
        ```
        Go 语言鼓励开发者在每个可能出错的地方显式地检查错误。函数返回错误时，调用者必须处理它。
    - 异常处理
        ```Go
        package main

        import "fmt"

        func main() {
            defer func() {
                if r := recover(); r != nil {
                    fmt.Println("恢复了:", r)
                }
            }()

            fmt.Println("开始")
            panic("发生了严重错误") // 引发 panic
            fmt.Println("结束") // 不会执行
        }
        ```
        - Go 没有异常处理机制，但它提供了 `panic` 和 `recover` 机制来处理严重错误。
        - `panic` 用于引发运行时错误，通常在程序检测到不可恢复的错误时使用。`recover` 可以在 `defer` 函数中捕获 `panic`，使程序能够恢复执行。
3. `panic`和`recover`的细节
    - `panic` 应该仅用于不可恢复的错误（如程序逻辑错误），而不是用于可预见的错误[//]: # ( 对于可预见的错误，使用返回值来处理错误，而不是使用 panic。)

        ```Go
        func openFile(filename string) {
            file, err := os.Open(filename)
            if err != nil {
                panic("无法打开文件: " + err.Error()) // 不推荐
            }
            defer file.Close()
        }

        ```
    - 如果在 goroutine 中发生 panic，而没有适当的 recover，整个程序将崩溃[//]: # (即上面的go func中不进行recover，那么整个程序就会崩掉。)

        ```Go
        func main() {
            go func() {
                defer func() {
                    recover() // 仅在这个 goroutine 中恢复
                }()
                panic("发生了严重错误")
            }()

            // 主 goroutine 继续执行
            fmt.Println("主 goroutine 继续执行")
            time.Sleep(time.Second) // 等待 goroutine 执行
        }

        ```